name: Actions ipkg Feed

on:
  workflow_call:
  schedule:
    #- cron: '*/5 * * * *'  # 每5分钟一次
    - cron: '0 0 */3 * *'  # 每3天运行一次
  workflow_dispatch:

env:
  Arch: "aarch64_generic x86_64"
  Repo: "https://3wlh:${{ secrets.TOKEN_GITHUB }}@github.com/3wlh/OpenWrt_Packages"
  

jobs:
  jobs_feed:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Initialization environment
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        
    - name: Git Clone Repositories
      uses: 3wlh/actions/openwrt/feed@main
      id: feed
      env:
        url: ${{ env.Repo }}
      
    - name: Download aarch64_generic Packages
      env: 
        Path: ${{ steps.feed.outputs.path }}
      run: |
        Packages_all "aarch64_generic" "${Path}"
        test -d "${Path}/packages/aarch64_generic" || \
        mkdir -p "${Path}/packages/aarch64_generic"
        find "/tmp/packages/aarch64_generic" -type f -name "*.[ia]pk" -exec mv -f {} "${Path}/packages/aarch64_generic" \;
    
    - name: Download x86_64 Packages
      env: 
        Path: ${{ steps.feed.outputs.path }}
      run: |
        Packages_all "x86_64" "${Path}"
        test -d "${Path}/packages/x86_64" || \
        mkdir -p "${Path}/packages/x86_64"
        find "/tmp/packages/x86_64" -type f -name "*.[ia]pk" -exec mv -f {} "${Path}/packages/x86_64" \;      
            
    - name: Create Repositories index
      working-directory: ${{ steps.feed.outputs.path }}
      run: |
        # gzip -k9 Packages
        Arch=(${{ env.Arch }})
        echo -e "${{ secrets.KEY }}" > /tmp/mime.key
        cd $(pwd)/packages
        for arch in "${Arch[@]}"; do
          [[ -d "${arch}" ]] && ipkg-make-index ${arch} > ${arch}/Packages
          [[ -f "${arch}/Packages" ]] && \
          gzip -fk9c ${arch}/Packages > ${arch}/Packages.gz && \
          usign -S -m ${arch}/Packages -s /tmp/mime.key -x ${arch}/Packages.sig
        done
    
    - name: Git Erase Commits
      working-directory: ${{ steps.feed.outputs.path }}
      run: |
        Emoji=("📦" "🧹" "🔄" "🚀" "✨" "🔧" "🛠️" "⚡" "🎯" "♻️" "🔄" "📦")
        # 添加所有文件
        git add -A
        # 提交更改
        git commit -am "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} update $(date +%Y-%m-%d" "%H:%M:%S)"
        # 清理优化Git仓库
    
    - uses: 3wlh/actions/git/remove-files@main
      with:
        repo_url: ${{ env.Repo }}
        repo_path: ${{ steps.feed.outputs.path }}
        
  jod_workflow: 
    needs: jobs_feed
    uses: ./.github/workflows/Actions_Remove_Workflow.yml
    secrets: inherit
    with:
      reuse: true