name: Call SDK Download

on:
  workflow_call:
    inputs:
      cache:
        type: boolean
      feeds:
        type: boolean  
      pack:
        type: boolean
      out:
        type: boolean
      cnb:
        type: boolean
      sdk:
        type: string
      package:
        type: string
      version:
          type: string

env:
  PACKAGE: ${{ inputs.package }}
  CACHE_PATH: /tmp/.cache
  OUTPUT_PATH: ${{ github.workspace }}/Output
  TZ: Asia/Shanghai
  UPLOAD_BIN_DIR: false

jobs:
  jod_initial:
    name: Actions Build ${{ inputs.package }}
    runs-on: ubuntu-latest
    outputs:
      time: ${{steps.output_time.outputs.time}}
    steps: 
      - name: output Time
        id: output_time
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "time=$(date "+%Y.%m.%d_%H%M%S")" >> $GITHUB_OUTPUT
        
      - name: Delete GitHub Release
        uses: dev-drprasad/delete-tag-and-release@master
        with:
          repo: 3wlh/OpenWrt_Packages
          tag_name: GitHub-Actions_${{ inputs.package }}
          delete_release: true
          github_token: ${{ secrets.TOKEN_GITHUB }}
        continue-on-error: true
      
      - name: Delete CNB Release
        if: (inputs.cnb == true)
        uses: 3wlh/actions/CNB/delete-releases@main
        with:
          repository: 3wlh/OpenWrt_Packages
          tag_name: GitHub-Actions_${{ inputs.package }}
          token: ${{ secrets.TOKEN_CNB }}
        continue-on-error: true
      
      - name: Cleanup GitHub Cache
        if: (inputs.cache == true)
        continue-on-error: true
        run: gh cache delete --all --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ github.token }}



  jod_build:
    name: Build Architecture ${{ matrix.arch }}
    needs: jod_initial
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64_generic,x86_64]
    env:
      BUILD_TIME: ${{ needs.jod_initial.outputs.time }}
      BUILD_FILENAME: ${{ inputs.package }}-${{ inputs.version }}-${{ matrix.arch }}_${{ needs.jod_initial.outputs.time }}.tar.gz
      
    steps: 
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y ccache gettext libncurses5-dev xsltproc

      - name: Initialization Settings
        run: |
          # ✅初始化设置
          test -d "${{ env.CACHE_PATH }}" || mkdir -pm 755 "${{ env.CACHE_PATH }}"
          test -d "${{ env.OUTPUT_PATH }}" || mkdir -pm 755 "${{ env.OUTPUT_PATH }}"
          if [ "${{ inputs.out }}" == "true" ]; then
            echo "Buildout=99" >> $GITHUB_ENV
          fi

      - name: Install and Unzip SDK
        uses: 3wlh/actions/openwrt/sdk@main
        id: sdk
        with:
          arch: ${{ matrix.arch }}
          version: ${{ inputs.version }}
          path: ${{ env.CACHE_PATH }}
        
          
      - name: Update and Install Packages
        working-directory: ${{ env.CACHE_PATH }}
        run: |
          # ✅ 复制源码文件
          # ./scripts/feeds update -a >/dev/null 2>&1
          find "${{ github.workspace }}" -maxdepth 1 -exec ln -s {} "package/" \;
          ./scripts/feeds install -a >/dev/null 2>&1
          # ./scripts/feeds install luci >/dev/null 2>&1
   
      - name: Build Packages
        working-directory: ${{ env.CACHE_PATH }}
        run: |
          # ✅ 编译源码文件
          make defconfig  >/dev/null
          make package/${{ env.PACKAGE }}/{clean,compile} V=${{ env.Buildout }} CONFIG_AUTOREMOVE=y 
          # make package/${{ env.PACKAGE }}/{clean,compile} 
          find "$(pwd)/bin/" -type f -name "*.[ai]pk" -exec ls -lh {} \;

      - name: Create compress files
        id: compress_file
        env: 
          pack: ${{ inputs.pack }}
          Package: ${{ env.PACKAGE }}
          Build_NAME: ${{ env.BUILD_FILENAME }}
          Build_PATH: ${{ env.CACHE_PATH }}/bin/packages/
          Output_FILE: ${{ env.OUTPUT_PATH }}/${{ env.BUILD_FILENAME }}
        run: |
          # 处理编译文件
          file=$(find "${Build_PATH}/" -name "*${Package}*.[ai]pk" | tail -1)
          file_path="$(dirname ${file})"
          echo "✅ 文件目录: ${file_path}"
          if [ -d "$file_path" ] && [ "$(ls -A $file_path)" ]; then
            test -d "${file_path}/tmp" && rm -fr "${file_path}/tmp"
            if [ "${{ inputs.pack }}" == "true" ]; then
              # 只执行一次tar命令，保留文件结构
              tar -zcf ${Output_FILE} -C $file_path .
              echo "✅ 压缩文件成功：${Output_FILE}"
            else
              # 复制文件到输出目录
              cp -f $file_path/* ${{ env.OUTPUT_PATH }}/
            fi
            test -d "${Build_PATH}" && rm -rf "${Build_PATH}"
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ 目标目录无文件：$file_path"
            echo "status=failed" >> $GITHUB_OUTPU
          fi
          find "${{ env.OUTPUT_PATH }}" -name "*.*" -exec ls -lh {} \;

      - name: Upload to bin directory
        uses: actions/upload-artifact@main
        if: ${{ env.UPLOAD_BIN_DIR == 'true' }} 
        with:
          name: ${{ matrix.arch }}_package_${{ env.BUILD_TIME }}
          path: ${{ env.CACHE_PATH }}/bin

      
      - name: Upload as release assets GitHub
        if: (steps.compress_file.outputs.status == 'success')
        uses: softprops/action-gh-release@master
        with:
          repository: 3wlh/OpenWrt_Packages
          token: ${{ secrets.TOKEN_GITHUB }}
          tag_name: GitHub-Actions_${{ env.PACKAGE }}
          name: Package：${{ env.PACKAGE }}
          files: ${{ env.OUTPUT_PATH }}/*
          body: |
            ## 软件信息：
            - 编译时间：`${{ env.BUILD_TIME }}`
            - SDK版本: `${{ inputs.version }}`
            
      - name: Upload as release assets CNB
        if: (inputs.cnb == true && steps.compress_file.outputs.status == 'success')
        uses: 3wlh/actions/CNB/upload-releases@main
        with:
          repository: 3wlh/OpenWrt_Packages
          token: ${{ secrets.TOKEN_CNB }}
          tag_name: GitHub-Actions_${{ env.PACKAGE }}
          name: Package：${{ env.PACKAGE }}
          files: ${{ env.OUTPUT_PATH }}/*
          body: |
            ## 软件信息：
            - 编译时间：`${{ env.BUILD_TIME }}`
            - SDK版本: `${{ inputs.version }}`